spring.application.name=quiz-app
server.port=8080
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:question_app}
spring.datasource.username=${POSTGRES_USER:question_app_user}
spring.datasource.password=${POSTGRES_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
